# SQLALCHEMY_DATABASE_URL = "postgresql://admin:password1234@tymkiv.pp.ua:5432/postgres"
SQLALCHEMY_DATABASE_URL = "sqlite:///./sql_app.db"

API_V1_STR = "/api/v1"


SECRET_KEY = "qqZcd9SimNNMwm+5wV+83HbXOB2JwIQYO9Bz7PjHlEI="

ACCESS_TOKEN_EXPIRE_MINUTES = 30

FIRST_SUPERUSER = "user@example.com"
FIRST_SUPERUSER_PASSWORD = "123456"


USERS_OPEN_REGISTRATION = True